const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const source=fs.readFileSync(path.resolve(__dirname,'../../assets/js/appearance.js'),'utf8');
test('parallax coalesces scroll updates, stays within the image margin, and stops when disabled',async()=>{
 const dom=new JSDOM('<!doctype html><html data-background="rainy-city" data-theme="light"><body><main>Gallery</main></body></html>',{url:'http://localhost',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,root=w.document.documentElement,frames=new Map();let next=0,hidden=false;
 const motion={matches:false,addEventListener(_event,fn){this.changed=fn}};
 w.matchMedia=q=>q.includes('reduced-motion')?motion:{matches:true,addEventListener(){}};
 w.requestAnimationFrame=fn=>{frames.set(++next,fn);return next};
 w.cancelAnimationFrame=id=>frames.delete(id);
 Object.defineProperty(w,'innerHeight',{value:1000});
 Object.defineProperty(root,'scrollHeight',{value:3000,configurable:true});
 Object.defineProperty(w.document,'hidden',{get:()=>hidden});
 const flush=()=>{const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn())};
 w.eval(source);w.document.dispatchEvent(new w.Event('DOMContentLoaded',{bubbles:true}));
 const layer=w.document.querySelector('.rustdl-city-backdrop');
 assert.ok(layer);assert.equal(layer.getAttribute('aria-hidden'),'true');
 const picture=layer.querySelector('.rustdl-city-image');
 assert.equal(frames.size,1);flush();
 assert.equal(picture.style.transform,'translate3d(0,40.00px,0)');
 w.scrollY=1000;
 for(let i=0;i<20;i++)w.dispatchEvent(new w.Event('scroll'));
 assert.equal(frames.size,1);flush();
 assert.equal(picture.style.transform,'translate3d(0,0.00px,0)');
 w.scrollY=100000;w.dispatchEvent(new w.Event('scroll'));flush();
 assert.equal(picture.style.transform,'translate3d(0,-40.00px,0)');
 w.dispatchEvent(new w.Event('scroll'));hidden=true;w.document.dispatchEvent(new w.Event('visibilitychange'));
 assert.equal(frames.size,0);
 hidden=false;w.document.dispatchEvent(new w.Event('visibilitychange'));assert.equal(frames.size,1);
 motion.matches=true;motion.changed();assert.equal(frames.size,0);assert.equal(root.dataset.cityParallax,'off');
 motion.matches=false;motion.changed();flush();assert.equal(root.dataset.cityParallax,'on');
 w.document.body.classList.add('pip');await Promise.resolve();assert.equal(root.dataset.cityParallax,'off');
 w.document.body.classList.remove('pip');await Promise.resolve();flush();
 w.RustDLTheme.receive('dark',true,'space');assert.equal(root.dataset.cityParallax,'off');assert.equal(frames.size,0);
 w.RustDLTheme.receive('dark',true,'rainy-city');assert.equal(root.dataset.cityParallax,'on');
 Object.defineProperty(root,'scrollHeight',{value:1000});flush();assert.equal(picture.style.transform,'translate3d(0,0.00px,0)');
 dom.window.close();
});

test('sunrise plays locally, reverses for sunset, and cancels for rapid toggles and reduced motion',async()=>{
 const dom=new JSDOM('<html data-background="rainy-city" data-theme="dark"><body></body></html>',{url:'http://localhost',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,root=w.document.documentElement,records=[];
 const motion={matches:false,addEventListener(_event,fn){this.changed=fn}};
 w.matchMedia=q=>q.includes('reduced-motion')?motion:{matches:false,addEventListener(){}};
 for(let i=1;i<=12;i++)root.style.setProperty('--rustdl-sunrise-'+i,`url("/frame-${i}.webp")`);
 root.style.setProperty('--rustdl-page-background-image','url("/night.webp")');
 let loads=0;
 w.Image=class {set src(value){loads++;queueMicrotask(()=>this.onload())}};
 w.Element.prototype.animate=function(keyframes,options){
  let finish;const record={element:this,options,cancelled:false,finished:new Promise(resolve=>{finish=resolve}),cancel(){this.cancelled=true},finish:()=>finish()};records.push(record);return record;
 };
 w.eval(source);w.document.dispatchEvent(new w.Event('DOMContentLoaded',{bubbles:true}));
 const settle=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
 w.RustDLTheme.apply('light',true,false,false);await settle();
 assert.equal(loads,12);assert.equal(records.length,13);
 assert.match(records[0].element.style.backgroundImage,/frame-1/);
 assert.match(records[11].element.style.backgroundImage,/frame-12/);
 w.RustDLTheme.apply('dark',true,false,false);await settle();
 assert.ok(records.slice(0,13).every(r=>r.cancelled));assert.equal(loads,12);
 assert.match(records[13].element.style.backgroundImage,/frame-12/);
 assert.match(records[24].element.style.backgroundImage,/frame-1/);
 records[25].finish();await settle();assert.equal(w.document.querySelector('.rustdl-sunrise'),null);
 w.RustDLTheme.apply('light',true,false,false);await settle();
 w.RustDLTheme.apply('light',true,false,false,'rainy-city',true);await settle();
 assert.equal(w.document.querySelector('.rustdl-sunrise'),null);assert.equal(root.dataset.cityParallax,'off');
 const pausedCount=records.length;w.RustDLTheme.apply('dark',true,false,false);await settle();assert.equal(records.length,pausedCount);
 w.RustDLTheme.apply('dark',true,false,false,'rainy-city',false);assert.equal(root.dataset.cityParallax,'on');
 w.RustDLTheme.apply('light',true,false,false);await settle();
 motion.matches=true;motion.changed();assert.equal(w.document.querySelector('.rustdl-sunrise'),null);
 const count=records.length;w.RustDLTheme.apply('dark',true,false,false);await settle();assert.equal(records.length,count);
 dom.window.close();
});
