//! Synthetic inspection pages and locally rendered inspection assets.

use super::super::local;
use std::error::Error;
use std::fs;
use std::path::Path;
use tiny_http::{Request, Response, StatusCode};

pub(in super::super) enum InspectionScreen {
    Result,
    Player,
}

pub(in super::super) fn respond_inspection_page(
    request: Request,
    screen: InspectionScreen,
) -> Result<(), Box<dyn Error>> {
    let (title, eyebrow, heading, detail, status, filename, transition_name) = match screen {
        InspectionScreen::Result => (
            "Synthetic progressive download",
            "Download status",
            "Streaming now.",
            "Synthetic state only. The player demonstrates watching while bytes arrive without resolving a link, making a network request, or reading a user file.",
            "Downloading",
            "Downloads/RustDL/synthetic-preview.mp4",
            "video-synthetic-download",
        ),
        InspectionScreen::Player => (
            "Synthetic video player",
            "RustDL player",
            "Ready when you are.",
            "This poster and filename are generated by RustDL for safe UI inspection.",
            "No user data",
            "synthetic-preview.mp4",
            "video-synthetic-preview",
        ),
    };
    let player_css = local::web_assets::player_css_path();
    let view_transition_script = local::web_assets::view_transition_script_tag();
    let body = format!(
        include_str!("../../assets/html/inspection-player.html"),
        detail = detail,
        eyebrow = eyebrow,
        filename = filename,
        heading = heading,
        player_css = player_css,
        status = status,
        title = title,
        transition_name = transition_name,
        view_transition_script = view_transition_script
    );
    let response = Response::from_string(local::web_assets::decorate_app_html(body))
        .with_status_code(StatusCode(200))
        .with_header(local::html::header(
            "Content-Type",
            "text/html; charset=utf-8",
        ))
        .with_header(local::html::html_csp())
        .with_header(local::html::header("Cache-Control", "no-store"))
        .with_header(local::html::header("X-Content-Type-Options", "nosniff"));
    request.respond(response)?;
    Ok(())
}

pub(in super::super) fn respond_inspection_poster(request: Request) -> Result<(), Box<dyn Error>> {
    const POSTER: &str = include_str!("../../assets/inspection-poster.svg");
    let response = Response::from_string(POSTER)
        .with_status_code(StatusCode(200))
        .with_header(local::html::header(
            "Content-Type",
            "image/svg+xml; charset=utf-8",
        ))
        .with_header(local::html::header("Cache-Control", "no-store"))
        .with_header(local::html::header("X-Content-Type-Options", "nosniff"));
    request.respond(response)?;
    Ok(())
}

pub(in super::super) fn respond_inspection_capture(
    request: Request,
    output_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    let capture = output_dir.join("inspection-capture.png");
    if !capture.is_file() {
        return local::html::respond_text(request, 404, "Inspection render is not ready");
    }
    let response = Response::from_data(fs::read(capture)?)
        .with_status_code(StatusCode(200))
        .with_header(local::html::header("Content-Type", "image/png"))
        .with_header(local::html::header("Cache-Control", "no-store"))
        .with_header(local::html::header("X-Content-Type-Options", "nosniff"));
    request.respond(response)?;
    Ok(())
}
